"""replace_skills_with_category_age_altphone

Revision ID: 16515e015806
Revises: ee96166bb6df
Create Date: 2026-03-06 20:59:08.187078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16515e015806'
down_revision: Union[str, None] = 'ee96166bb6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sub_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alt_phone', sa.String(length=20), nullable=True))
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.TEXT(), nullable=True))
        batch_op.drop_column('alt_phone')
        batch_op.drop_column('age')
        batch_op.drop_column('sub_category')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
