"""Add MagicLink model

Revision ID: 7358fe0094ea
Revises: 7ebf6acf4118
Create Date: 2026-03-11 22:18:13.255666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7358fe0094ea'
down_revision: Union[str, None] = '7ebf6acf4118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
