"""Initial schema

Revision ID: 7708f84c4cff
Revises: 
Create Date: 2026-07-02 18:56:19.710468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7708f84c4cff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('last_user_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_states_wa_number'), ['wa_number'], unique=True)

    op.create_table('gethelp_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gethelp_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gethelp_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gethelp_requests_wa_number'), ['wa_number'], unique=False)

    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_links_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_magic_links_wa_number'), ['wa_number'], unique=False)

    op.create_table('otp_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_records_wa_number'), ['wa_number'], unique=False)

    op.create_table('recruiter_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('business_contact', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruiter_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruiter_table_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruiter_table_wa_number'), ['wa_number'], unique=True)

    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('free_trial', 'basic', 'popular', 'advanced', name='plan_name'), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('price_inr', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('max_applications', sa.Integer(), nullable=True),
    sa.Column('same_day_vacancy', sa.Boolean(), nullable=True),
    sa.Column('max_cv_updates', sa.Integer(), nullable=True),
    sa.Column('interview_scheduling', sa.Boolean(), nullable=True),
    sa.Column('vacancy_forward', sa.Boolean(), nullable=True),
    sa.Column('location_filter', sa.Boolean(), nullable=True),
    sa.Column('job_filter', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_id'), ['id'], unique=False)

    op.create_table('user_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('wa_number', sa.String(length=20), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_questions_id'), ['id'], unique=False)

    op.create_table('candidate_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('exact_location', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('alt_phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('cv_path', sa.String(length=500), nullable=True),
    sa.Column('cv_updates_used', sa.Integer(), nullable=True),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applications_used', sa.Integer(), nullable=True),
    sa.Column('free_trial_used', sa.Boolean(), nullable=True),
    sa.Column('registration_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_table_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_table_wa_number'), ['wa_number'], unique=True)

    op.create_table('job_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_code', sa.String(length=20), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('job_category', sa.String(length=50), nullable=False),
    sa.Column('district_region', sa.String(length=100), nullable=False),
    sa.Column('exact_location', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_mode', sa.String(length=50), nullable=False),
    sa.Column('experience_required', sa.String(length=100), nullable=False),
    sa.Column('salary_range', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('cv_required', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ad_stop_notification_pending', sa.Boolean(), nullable=False),
    sa.Column('milestone_pending_count', sa.Integer(), nullable=False),
    sa.Column('milestone_notified_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_vacancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_vacancies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_vacancies_job_code'), ['job_code'], unique=True)

    op.create_table('admin_notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['job_vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_notification_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_notification_queue_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_notification_queue_wa_number'), ['wa_number'], unique=False)

    op.create_table('candidate_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=500), nullable=False),
    sa.Column('category_tag', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_resumes_id'), ['id'], unique=False)

    op.create_table('candidate_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'shortlisted', name='application_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_table.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['candidate_resumes.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['job_vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_applications_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_applications_id'))

    op.drop_table('candidate_applications')
    with op.batch_alter_table('candidate_resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_resumes_id'))

    op.drop_table('candidate_resumes')
    with op.batch_alter_table('admin_notification_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_notification_queue_wa_number'))
        batch_op.drop_index(batch_op.f('ix_admin_notification_queue_id'))

    op.drop_table('admin_notification_queue')
    with op.batch_alter_table('job_vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_vacancies_job_code'))
        batch_op.drop_index(batch_op.f('ix_job_vacancies_id'))

    op.drop_table('job_vacancies')
    with op.batch_alter_table('candidate_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_table_wa_number'))
        batch_op.drop_index(batch_op.f('ix_candidate_table_id'))

    op.drop_table('candidate_table')
    with op.batch_alter_table('user_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_questions_id'))

    op.drop_table('user_questions')
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_id'))

    op.drop_table('subscription_plans')
    with op.batch_alter_table('recruiter_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiter_table_wa_number'))
        batch_op.drop_index(batch_op.f('ix_recruiter_table_id'))

    op.drop_table('recruiter_table')
    with op.batch_alter_table('otp_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_records_wa_number'))
        batch_op.drop_index(batch_op.f('ix_otp_records_id'))

    op.drop_table('otp_records')
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_links_wa_number'))
        batch_op.drop_index(batch_op.f('ix_magic_links_token'))
        batch_op.drop_index(batch_op.f('ix_magic_links_id'))

    op.drop_table('magic_links')
    with op.batch_alter_table('gethelp_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gethelp_requests_wa_number'))
        batch_op.drop_index(batch_op.f('ix_gethelp_requests_id'))

    op.drop_table('gethelp_requests')
    with op.batch_alter_table('conversation_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_states_wa_number'))
        batch_op.drop_index(batch_op.f('ix_conversation_states_id'))

    op.drop_table('conversation_states')
    # ### end Alembic commands ###
