"""add_milestone_columns_to_job_vacancies

Revision ID: 910cda367e81
Revises: c3f1a9b2e874
Create Date: 2026-07-01 12:24:44.293650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910cda367e81'
down_revision: Union[str, None] = 'c3f1a9b2e874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite cannot add a NOT NULL column via ALTER TABLE without a default
    # value for existing rows.  We supply server_default='0' so all existing
    # vacancy records start at 0 (no milestones notified/pending), which is
    # exactly the correct semantic for the new feature.
    with op.batch_alter_table('job_vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'milestone_pending_count',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ))
        batch_op.add_column(sa.Column(
            'milestone_notified_count',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_vacancies', schema=None) as batch_op:
        batch_op.drop_column('milestone_notified_count')
        batch_op.drop_column('milestone_pending_count')

    # ### end Alembic commands ###
