"""add_ad_lifecycle_columns

Revision ID: d8ff79fea3a4
Revises: 910cda367e81
Create Date: 2026-07-01 20:15:45.187845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ff79fea3a4'
down_revision: Union[str, None] = '910cda367e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_vacancies', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('job_vacancies', sa.Column('last_enabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_vacancies', sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_vacancies', sa.Column('ad_stop_notification_pending', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_vacancies', schema=None) as batch_op:
        batch_op.drop_column('ad_stop_notification_pending')
        batch_op.drop_column('stopped_at')
        batch_op.drop_column('last_enabled_at')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
